---
- name: Add user to groups
  uri:
    url: "{{ atlassian.url }}/rest/api/2/group/user?groupname={{ urlencode(item) }}"
    method: POST
    user: '{{ atlassian.username }}'
    password: '{{ atlassian.password }}'
    force_basic_auth: yes
    status_code: [201, 400]
    body_format: json
    body: "{ 'name': '{{ atlassian.create.user.email.split(\"@\") | first }}' }"
    return_content: yes
  with_items: '{{ atlassian.add_user_to_groups }}'
  when: atlassian_user.groups|length > 0
