---
- name: Add user to groups
  uri:
    url: "{{ atlassian_url }}/rest/api/2/group/user?groupname={{ urlencode(item) }}"
    method: POST
    user: '{{ atlassian_username }}'
    password: '{{ atlassian_password }}'
    force_basic_auth: yes
    status_code: [201, 400]
    body_format: json
    body: "{ 'name': '{{ atlassian_user.email.split(\"@\") | first }}' }"
    return_content: yes
  with_items: '{{ atlassian_user.groups }}'
  when: atlassian_user.groups|length > 0
