---
- name: Create User
  uri:
    url: '{{ atlassian.url }}/rest/api/2/user'
    method: POST
    user: '{{ atlassian.username }}'
    password: '{{ atlassian.password }}'
    force_basic_auth: yes
    status_code: 201
    body_format: json
    body: "{'name': '{{ atlassian.create.user.email.split(\"@\") | first }}', 
            'password': '{{ atlassian.create.user.password }}', 
            'emailAddress': '{{ atlassian.create.user.email }}', 
            'displayName': '{{ atlassian.create.user.firstname }} {{ atlassian.create.user.lastname }}' }"
    return_content: yes
  register: user_data
