---
- name: Create Confluence Space
  uri:
    url: '{{ confluence.destination.url }}/wiki/rest/api/space'
    method: POST
    user: '{{ confluence.destination.username }}'
    password: '{{ confluence.destination.password }}'
    force_basic_auth: yes
    status_code: 200
    body_format: json
    body: "{{ lookup('template', 'space.j2') }}"
